#!/usr/bin/env python3
import pyheif
from PIL import Image
import os


def convertHeic2Jpeg(urlImage):
    heif_file = pyheif.read(urlImage)
    filename, _ = os.path.splitext(urlImage)
    image = Image.frombytes(
        heif_file.mode, 
        heif_file.size, 
        heif_file.data,
        "raw",
        heif_file.mode,
        heif_file.stride,
        )
    image.save(filename + ".jpg", "JPEG")

    

def main():
    path = 'images/custom/'
    for file in os.listdir(path):
        if file.endswith('.heic'):
            convertHeic2Jpeg(path + file)


if __name__ == '__main__':
    main()
